// <auto-generated />
using System;
using BillingPlatform.Reporting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingPlatform.Reporting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260914180433_AddReportingIngestOrder")]
    partial class AddReportingIngestOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingPlatform.Reporting.Domain.MrrMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AfterAnnualizedCents")
                        .HasColumnType("bigint")
                        .HasColumnName("after_annualized_cents");

                    b.Property<long>("BeforeAnnualizedCents")
                        .HasColumnType("bigint")
                        .HasColumnName("before_annualized_cents");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long>("DeltaAnnualizedCents")
                        .HasColumnType("bigint")
                        .HasColumnName("delta_annualized_cents");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_mrr_movements");

                    b.HasIndex("OrganizationId", "Currency", "OccurredAt")
                        .HasDatabaseName("ix_mrr_movements_organization_id_currency_occurred_at");

                    b.HasIndex("OrganizationId", "SourceEventId", "SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_reporting_mrr_movements_organization_source_subscription");

                    b.ToTable("mrr_movements", "reporting");
                });

            modelBuilder.Entity("BillingPlatform.Reporting.Domain.ReportingSourceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("IngestOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ingest_order");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IngestOrder"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<int?>("PriceVersion")
                        .HasColumnType("integer")
                        .HasColumnName("price_version");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("source_type");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<int?>("SubscriptionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_version");

                    b.HasKey("Id")
                        .HasName("pk_source_events");

                    b.HasIndex("IngestOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_source_events_ingest_order");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .HasDatabaseName("ix_source_events_organization_id_occurred_at");

                    b.HasIndex("OrganizationId", "SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_reporting_source_events_organization_source");

                    b.HasIndex("OrganizationId", "PriceId", "PriceVersion")
                        .HasDatabaseName("ix_source_events_organization_id_price_id_price_version");

                    b.HasIndex("OrganizationId", "SubscriptionId", "SubscriptionVersion")
                        .HasDatabaseName("ix_source_events_organization_id_subscription_id_subscription_");

                    b.ToTable("source_events", "reporting");
                });

            modelBuilder.Entity("BillingPlatform.Reporting.Domain.SubscriptionRevenueSnapshot", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<long>("AnnualizedFixedCents")
                        .HasColumnType("bigint")
                        .HasColumnName("annualized_fixed_cents");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<bool>("EverRevenueBearing")
                        .HasColumnType("boolean")
                        .HasColumnName("ever_revenue_bearing");

                    b.Property<Guid>("LastSourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_source_event_id");

                    b.Property<bool>("MeteredExcluded")
                        .HasColumnType("boolean")
                        .HasColumnName("metered_excluded");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<int>("PriceVersion")
                        .HasColumnType("integer")
                        .HasColumnName("price_version");

                    b.Property<string>("PricingModel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pricing_model");

                    b.Property<int?>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_version");

                    b.HasKey("OrganizationId", "SubscriptionId")
                        .HasName("pk_subscription_snapshots");

                    b.HasIndex("OrganizationId", "PriceId")
                        .HasDatabaseName("ix_subscription_snapshots_organization_id_price_id");

                    b.HasIndex("OrganizationId", "Currency", "Status")
                        .HasDatabaseName("ix_subscription_snapshots_organization_id_currency_status");

                    b.ToTable("subscription_snapshots", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
