// <auto-generated />
using System;
using BillingPlatform.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingPlatform.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingPlatform.Catalog.Domain.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("billing_interval");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long?>("FlatUnitAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("flat_unit_amount_cents");

                    b.Property<string>("MeteredAggregation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("metered_aggregation");

                    b.Property<long?>("MeteredUnitAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("metered_unit_amount_cents");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long?>("PerSeatUnitAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("per_seat_unit_amount_cents");

                    b.Property<string>("PricingModel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pricing_model");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int?>("TrialDays")
                        .HasColumnType("integer")
                        .HasColumnName("trial_days");

                    b.HasKey("Id")
                        .HasName("pk_prices");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_prices_product_id");

                    b.HasIndex("OrganizationId", "ProductId")
                        .HasDatabaseName("ix_prices_organization_id_product_id");

                    b.ToTable("prices", "catalog");
                });

            modelBuilder.Entity("BillingPlatform.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("OrganizationId", "Name")
                        .HasDatabaseName("ix_products_organization_id_name");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("BillingPlatform.Catalog.Domain.Price", b =>
                {
                    b.HasOne("BillingPlatform.Catalog.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prices_products_product_id");

                    b.OwnsMany("BillingPlatform.Catalog.Domain.PricingTier", "Tiers", b1 =>
                        {
                            b1.Property<Guid>("price_id")
                                .HasColumnType("uuid")
                                .HasColumnName("price_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int?>("EndingUnit")
                                .HasColumnType("integer")
                                .HasColumnName("ending_unit");

                            b1.Property<int>("StartingUnit")
                                .HasColumnType("integer")
                                .HasColumnName("starting_unit");

                            b1.Property<long>("UnitAmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("unit_amount_cents");

                            b1.HasKey("price_id", "Id")
                                .HasName("pk_price_tiers");

                            b1.ToTable("price_tiers", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("price_id")
                                .HasConstraintName("fk_price_tiers_prices_price_id");
                        });

                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
