// <auto-generated />
using System;
using BillingPlatform.Organizations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingPlatform.Organizations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationsDbContext))]
    [Migration("20260909165132_InitialOrganizations")]
    partial class InitialOrganizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizations")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingPlatform.Organizations.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("invoice_prefix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("SimulationModeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("simulation_mode_enabled");

                    b.Property<string>("WebhookSecret")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("webhook_secret");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", "organizations");
                });

            modelBuilder.Entity("BillingPlatform.Organizations.Domain.OrganizationMembership", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("OrganizationId", "UserId")
                        .HasName("pk_organization_memberships");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_organization_memberships_user_id_created_at");

                    b.ToTable("organization_memberships", "organizations");
                });

            modelBuilder.Entity("BillingPlatform.Organizations.Domain.OrganizationMembership", b =>
                {
                    b.HasOne("BillingPlatform.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organizations_organization_id");
                });
#pragma warning restore 612, 618
        }
    }
}
