<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\BillingPlatform.Identity.Api\BillingPlatform.Identity.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\BillingPlatform.Identity.Application\BillingPlatform.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\BillingPlatform.Identity.Domain\BillingPlatform.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\BillingPlatform.Identity.Infrastructure\BillingPlatform.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organizations\BillingPlatform.Organizations.Api\BillingPlatform.Organizations.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organizations\BillingPlatform.Organizations.Application\BillingPlatform.Organizations.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organizations\BillingPlatform.Organizations.Domain\BillingPlatform.Organizations.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organizations\BillingPlatform.Organizations.Infrastructure\BillingPlatform.Organizations.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\BillingPlatform.Customers.Api\BillingPlatform.Customers.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\BillingPlatform.Customers.Application\BillingPlatform.Customers.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\BillingPlatform.Customers.Domain\BillingPlatform.Customers.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\BillingPlatform.Customers.Infrastructure\BillingPlatform.Customers.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\BillingPlatform.Catalog.Api\BillingPlatform.Catalog.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\BillingPlatform.Catalog.Application\BillingPlatform.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\BillingPlatform.Catalog.Domain\BillingPlatform.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\BillingPlatform.Catalog.Infrastructure\BillingPlatform.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\SimulationClock\BillingPlatform.SimulationClock.Application\BillingPlatform.SimulationClock.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\SimulationClock\BillingPlatform.SimulationClock.Infrastructure\BillingPlatform.SimulationClock.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Subscriptions\BillingPlatform.Subscriptions.Api\BillingPlatform.Subscriptions.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Subscriptions\BillingPlatform.Subscriptions.Application\BillingPlatform.Subscriptions.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Subscriptions\BillingPlatform.Subscriptions.Domain\BillingPlatform.Subscriptions.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Subscriptions\BillingPlatform.Subscriptions.Infrastructure\BillingPlatform.Subscriptions.Infrastructure.csproj" />
  </ItemGroup>

</Project>
